name: sistemium_flutter_auth
publish_to: "none"
version: 1.0.1
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 4.6.0
  get: 5.0.0-release-candidate-4
  loader_overlay: 2.2.0
  stm_extensions:
    git:
      url: https://github.com/EdgarJan/stm_extensions.git
      ref: '6c12e6a'
  pin_code_fields: 7.4.0
  google_sign_in: 6.1.0
  sign_button: 2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: